name: Build and release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Run linter tests
        run: |
          yarn
          yarn lint:test

      - name: Build and release
        uses: samuelmeuli/action-electron-builder@v1
        with:
          build_script_name: 'electron:prebuild'
          use_vue_cli: true
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
          github_token: ${{ secrets.github_token }}

          # Create a release draft only if commit has a tag 'v*'
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Create dir for artifacts
        run: |
          mkdir artifacts

      - name: Cleanup artifacts macOS
        if: matrix.os == 'macos-latest'
        run: cp ./dist_electron/*.dmg ./artifacts

      - name: Cleanup artifacts Linux
        if: matrix.os == 'ubuntu-latest'
        run: cp ./dist_electron/*.AppImage ./artifacts

      - name: Cleanup artifacts Win
        if: matrix.os == 'windows-latest'
        run: cp ./dist_electron/*.exe ./artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{matrix.os}}
          path: artifacts
