name: Build and release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Make envfile
        uses: codex-team/action-create-env@v1
        with:
          envkey_VUE_APP_API_URL: ${{ secrets.VUE_APP_API_URL }}
          envkey_VUE_APP_AUTH_TOKEN: ${{ secrets.VUE_APP_AUTH_TOKEN }}

      - name: Build and release
        uses: samuelmeuli/action-electron-builder@v1
        with:
          build_script_name: 'electron:prebuild'
          use_vue_cli: true
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
